### ISSUE TITLE
YACIS corpus download

### ISSUE THREAD

**Issue by alvations** [ptaszynski/mlask#1]
Is there a way to find/download the YACIS corpus?

**Comment by ptaszynski** [comment]
No. I stopped releasing my code and data to the public after a few Japanese professors stole my stuff and started using them as their own.

**Comment by alvations** [comment]
Got it. It's a pity to hear that =(

If there's anyway that you can be compensated for the work you have done and release the data, please do contact us. We'll be glad to work something out.
